require('plugins')
require('settings')
require('mappings')
require('colorbuddy').colorscheme('gruvbuddy')
require('lsp-cfg')
require('completion')
require('nvim_comment').setup()
require('gitsigns').setup{}
require('hardline').setup{}
require('snippets')
require('treesit')
